### ISSUE TITLE
System.MissingMethodException PuppeteerSharp.Puppeteer.LaunchAsync

### ISSUE THREAD

**Issue by KoalaBear84** [Overmiind/Puppeteer-sharp-extra#42]
New [PuppeteerSharp release](https://github.com/hardkoded/puppeteer-sharp/releases/tag/v8.0.0) breaks PuppeteerExtraSharp

System.MissingMethodException: 'Method not found: 'System.Threading.Tasks.Task`1<PuppeteerSharp.Browser> PuppeteerSharp.Puppeteer.LaunchAsync(PuppeteerSharp.LaunchOptions, Microsoft.Extensions.Logging.ILoggerFactory)'.'

```csharp
Browser = await new PuppeteerExtra().LaunchAsync(new LaunchOptions());
```

**Comment by FahadAltaf** [comment]
Revert puppeteersharp package to 7.1.0 with 8.0.0 its not working

**Comment by KoalaBear84** [comment]
Yes, that's why I made the issue.

**Comment by orentet** [comment]
I'd also would like to know when this will be solved?

**Comment by namilkimfree** [comment]
After checking, I will make a custom version.

**Comment by FahadAltaf** [comment]
I am able to fix this issue buy upgrading to .NET 6. Just download this package instead of default one
https://www.nuget.org/packages/PuppeteerExtraSharp6

**Comment by namilkimfree** [comment]
Fixed this issue 

https://github.com/Overmiind/Puppeteer-sharp-extra/pull/46

Custom link: https://www.nuget.org/packages/PuppeteerExtraSharp-Custom/

**Comment by Overmiind** [comment]
Fixed by [R3D4NG3L](https://github.com/Overmiind/Puppeteer-sharp-extra/pull/49)
Please update the NuGet package version of Puppeteer Extra Sharp to 2.0.

**Comment by RichJacobs** [comment]
Am using Puppeteer Extra Sharp to 2.0. and still get this issue
